[package]
name = "test_plugin"
version = "0.0.1"
authors = ["the deno authors"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
deno_core = { git = "https://github.com/denoland/deno.git", branch = "main" }
futures = "0.3.14"
serde = "1.0.125"
