name: CI check

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      
    - name: Setup latest deno version
      uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x

    - name: Check deno fmt
      run: deno fmt --check
    
    - name: Check deno lint
      run: deno lint --unstable
      
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      
    - name: Setup latest deno version
      uses: denolib/setup-deno@v2
      with:
        deno-version: v1.x

    - name: Install stable rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Run cargo build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --manifest-path=test_plugin/Cargo.toml

    - name: Run deno test
      run: deno test -A --unstable